language: python
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7'
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
script:
    - flake8
    - nose2
